In [69]:
import pandas as pd
import keras
import string
import nltk
import sklearn
data=pd.read_csv('semeval-2013-dev.csv', delimiter = '\t')
##for i in range(len(data))

data.describe()
data.columns=['l','text']
data.iloc[1,1]



'@CMPunk Devil Inside , The exorcisism of Emily Rose , Wrong Turn 4 , See no evil with Kane and Friday the 13th.'

In [70]:

##for i in range(len(data))

data.describe()
data.columns=['l','text']

data["text"]
data.iloc[0,1]=data.iloc[0,1].lower()
data.iloc[0,1]

for i in range(len(data)):
    data.iloc[i,1]=data.iloc[i,1].lower()
    
data
print(type(data.iloc[0,1]))
        


<class 'str'>


In [71]:
from nltk.tokenize import word_tokenize


In [72]:
from nltk.corpus import stopwords
stop=stopwords.words('english')
p=list(string.punctuation)
stop=stop+p


In [73]:

ds=[]
all_words=[]

for i in range(len(data)):
     words=word_tokenize(data.iloc[i,1])
     clean_words=[w for w in words if not w in stop]  
     ds.append((data.iloc[i][0],clean_words))
     
data.head(10)    





l                                               text
0  0  watching devil inside for the 1st time tonight...
1  0  @cmpunk devil inside , the exorcisism of emily...
2  0  off to do my vlog. watching devil inside and j...
3  1  @raykipo take silver at the hib cup. great day...
4  0  @hollyhippo i'm going to blockbuster tomorrow ...
5  0  watching devil inside for the 2nd time and i'm...
6  1  a blast from the past... daisy may's should ha...
7  0  @zeeayy @shazvampz hahahaha! busted. i just me...
8  1  : the dark knight rises. seeing it for the 3rd...
9  0  @brian_munoz97 @spencer_reece @mnemosyne_love ...

In [121]:
z=[data.iloc[0][0]]  
for i in range(1,len(data)):
    z+=[data.iloc[i][0]]  
len(z)

       





len(z)

1650

In [122]:
 l=[" ".join(ds[0][1])]
for i in range(1,1650):
    
    l+=[" ".join(ds[i][1])]
    



len(l)
s=[",".join(l)]
s


["watching devil inside 1st time tonight ohbabyjesus,cmpunk devil inside exorcisism emily rose wrong turn 4 see evil kane friday 13th,vlog watching devil inside journey 2 mysterious island tomorrow ... http //t.co/k0ep0ggs,raykipo take silver hib cup great day see ukparachuting boogie starting tomorrow,hollyhippo 'm going blockbuster tomorrow get devil inside 's okay,watching devil inside 2nd time 'm freeking cry,blast past ... daisy may 's received golden globe one lol http //t.co/p4nzufon,zeeayy shazvampz hahahaha busted met hib today hahaha ok monday kiter buke together gether free labour included tak o.o,dark knight rises seeing 3rd time lol early start talking golden globe oscar nods best everything,brian_munoz97 spencer_reece mnemosyne_love 's city california march rose parade new years disney land parade,holy c0w time halloween got possession aug 30 pa4 oct 19 hope god 'll better devil inside,bout watch joyful noise 110 000 time 2nd favorite movie,videos rehearsals videos perfor

In [123]:
##from sklearn_feeature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer
count_vec=CountVectorizer(max_features=50)
a=count_vec.fit_transform(l)

a.shape
##a is not a list but maybe z is a list 
##count_vec.get_feature_names()
a=pd.DataFrame(a.todense())
z=pd.DataFrame(z)
count_vec.get_feature_names()
z
a


0   1   2   3   4   5   6   7   8   9   ...  40  41  42  43  44  45  46  \
0      1   0   0   0   0   0   0   0   0   0  ...   0   0   1   0   1   0   0   
1      0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
2      0   0   0   0   0   0   0   0   1   0  ...   0   0   0   1   0   0   0   
3      0   0   0   0   0   0   0   0   0   0  ...   0   0   0   1   0   0   0   
4      0   0   0   0   0   0   0   0   0   0  ...   0   0   0   1   0   0   0   
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
1645   0   0   0   0   0   1   0   0   0   0  ...   0   0   0   0   0   0   0   
1646   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   1   0   0   0   
1647   0   0   0   0   0   0   0   1   0   0  ...   1   0   0   1   0   0   0   
1648   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   1   0   0   0   
1649   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   

      47  48  49  
0      0   0   0  
1      0   0   0  
2      0   0   0  
3      0   0   0  
4      0   0   0  
...   ..  ..  ..  
1645   0   0   0  
1646   0   0   0  
1647   0   0   0  
1648   0   0   0  
1649   0   0   0  

[1650 rows x 50 columns]

In [124]:
from sklearn.model_selection import train_test_split
xt1,xt2,yt1,yt2=train_test_split(a,z,test_size=0.3)



xt1.shape
len(yt1)

len(xt2)
len(xt2)
z

0
0     0
1     0
2     0
3     1
4     0
...  ..
1645  1
1646  0
1647 -1
1648  0
1649  0

[1650 rows x 1 columns]

In [125]:
import numpy as np
yt1=np.array(yt1)
yt2=np.array(yt2)
xt2=np.array(xt2)
xt1=np.array(xt1)

yt1=yt1.ravel()
yt2=yt2.ravel()
yt1.shape
yt2.shape
z=np.array(z)
z=z.ravel()
z

array([ 0,  0,  0, ..., -1,  0,  0], dtype=int64)

### from sklearn.linear_model import LogisticRegression

In [126]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(solver='liblinear',multi_class='ovr')

In [127]:
from sklearn.model_selection import cross_val_score

In [128]:
p=cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),a,z,cv=10)

In [129]:
p

array([0.46385542, 0.45180723, 0.51204819, 0.56363636, 0.52727273,
       0.50909091, 0.51515152, 0.52439024, 0.51219512, 0.53658537])

In [130]:
model.fit(xt1,yt1)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='ovr', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [131]:
model.score(xt2,yt2)

0.5050505050505051

In [132]:
yp=model.predict(xt2)
yp=np.reshape(yp,(yp.shape[0],1))

yt2.shape
yp.shape

(495, 1)

In [133]:
from sklearn.metrics import confusion_matrix

In [134]:
confusion_matrix(yt2,yp)

array([[ 10,  72,  34],
       [ 11, 175,  27],
       [  3,  98,  65]], dtype=int64)

In [135]:
from sklearn.metrics import classification_report
print(classification_report(yt2,yp))

              precision    recall  f1-score   support

          -1       0.42      0.09      0.14       116
           0       0.51      0.82      0.63       213
           1       0.52      0.39      0.45       166

    accuracy                           0.51       495
   macro avg       0.48      0.43      0.41       495
weighted avg       0.49      0.51      0.45       495



In [52]:
from sklearn.svm import SVC

In [53]:
model=SVC(kernel='linear',C=1).fit(xt1,yt1)

In [54]:
yp=model.predict(xt2)

In [55]:
model.score(xt2,yt2)

0.5414141414141415

In [56]:
from sklearn.metrics import confusion_matrix

In [57]:
confusion_matrix(yt2,yp)

array([[ 32,  47,  29],
       [ 25, 166,  34],
       [ 22,  70,  70]], dtype=int64)

In [58]:
from sklearn.metrics import classification_report

In [59]:
print(classification_report(yt2,yp))

              precision    recall  f1-score   support

          -1       0.41      0.30      0.34       108
           0       0.59      0.74      0.65       225
           1       0.53      0.43      0.47       162

    accuracy                           0.54       495
   macro avg       0.51      0.49      0.49       495
weighted avg       0.53      0.54      0.53       495



In [60]:
l=cross_val_score(SVC(kernel='linear',C=2,gamma='scale'),xt1,yt1,cv=10)
l

array([0.51694915, 0.47008547, 0.46086957, 0.62608696, 0.46086957,
       0.4       , 0.53043478, 0.49565217, 0.53043478, 0.47826087])

In [61]:
l.mean()

0.4969643318280018

In [31]:
xt1.shape
    
    

(1155, 250)

In [272]:
from keras.models import Sequential
from keras.layers import Dense, Flatten, LSTM, Conv1D, MaxPooling1D, Dropout, Activation
from keras.layers.embeddings import Embedding
model = Sequential()
model.add(Embedding(20000, 100, input_length=250))
model.add(LSTM(100, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

In [273]:
model.fit(xt1, yt1, validation_split=0.4, epochs=10)

C:\Users\Mainak Ghosh\Anaconda3\lib\site-packages\tensorflow_core\python\framework\indexed_slices.py:424: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Train on 693 samples, validate on 462 samples
Epoch 1/10
693/693 [==============================] - 7s 10ms/step - loss: 0.5245 - accuracy: 0.8052 - val_loss: 0.5259 - val_accuracy: 0.7857
Epoch 2/10
693/693 [==============================] - 7s 10ms/step - loss: 0.5050 - accuracy: 0.8052 - val_loss: 0.5290 - val_accuracy: 0.7857
Epoch 3/10
693/693 [==============================] - 7s 10ms/step - loss: 0.4991 - accuracy: 0.8052 - val_loss: 0.5285 - val_accuracy: 0.7857
Epoch 4/10
693/693 [==============================] - 6s 9ms/step - loss: 0.5021 - accuracy: 0.8052 - val_loss: 0.5281 - val_accuracy: 0.7857
Epoch 5/10
693/693 [==============================] - 6s 8ms/step - loss: 0.4923 - accuracy: 0.8052 - val_loss: 0.5213 - val_accuracy: 0.7857
Epoch 6/10
693/693 [==============================] - 6s 9ms/step - loss: 0.5006 - accuracy: 0.8052 - val_loss: 0.5379 - val_accuracy: 0.7857
Epoch 7/10
693/693 [==============================] - 6s 9ms/step - loss: 0.4966 - accuracy: 0.8052

In [274]:
##xt2=np.reshape(xt2,(xt2.shape[0],xt2.shape[1],1))
yp=model.predict(xt2)
yp.shape
##loss and accuracy
model.evaluate(xt2,yt2)




495/495 [==============================] - 1s 2ms/step


[0.52823141102839, 0.7858585715293884]